version: "3.4"

services:
  redis:
    container_name: ts-auth-redis
    image: redis:alpine
    restart: always
    ports:
      - 6377:6379
    volumes:
      - ./volumes/redis-data:/data

  postgres:
    container_name: ts-auth-postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ts-auth
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./postgres_migration:/docker-entrypoint-initdb.d

  api:
    container_name: ts-auth-debug
    image: samialateya/ts-auth:1.0.0
    build:
      context: .
      target: debug
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ts-auth
    volumes:
    - ./src/:/usr/app/src/