version: "3.4"

services:
  api:
    container_name: ts-auth-debug
    image: samialateya/ts-auth:1.0.0
    build:
      context: .
      target: debug
    volumes:
    - ./src/:/usr/app/src/
    ports:
      - 3000:3000